name: multi_logger_example
description: An example of using multi_logger package
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  multi_logger: ^0.0.1
  sentry: ^8.14.2
